# Generated by Django 2.2.5 on 2020-03-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='es', max_length=10)),
                ('locale', models.CharField(default='es-gt', max_length=10)),
                ('title', models.CharField(max_length=144)),
                ('rich_post_content', models.TextField()),
                ('plain_post_content', models.TextField()),
                ('link_post', models.CharField(max_length=144)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
