# Generated by Django 2.2.5 on 2020-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postlocale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(default='es', max_length=16),
        ),
    ]
