# Generated by Django 2.2.5 on 2020-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_question_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlocale',
            name='summary_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
