# Generated by Django 2.2.10 on 2020-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200310_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area_id',
            field=models.IntegerField(choices=[(1, 'Cognitivo'), (2, 'Motor'), (3, 'Emocional')], default=1, null=True, verbose_name='Area'),
        ),
    ]
