# Generated by Django 2.2.10 on 2020-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200512_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocale',
            name='locale',
            field=models.CharField(choices=[('en_US', 'en_US'), ('es_LA', 'es_LA'), ('ar_EA', 'ar_EA')], default='en_US', max_length=10),
        ),
    ]
