# Generated by Django 2.2.13 on 2020-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_materiales_situacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='materiales',
            field=models.ManyToManyField(to='posts.Materiales'),
        ),
        migrations.AddField(
            model_name='post',
            name='situacional',
            field=models.ManyToManyField(to='posts.Situacional'),
        ),
    ]
