# Generated by Django 2.2.13 on 2020-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200810_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cantidad_materiales',
            field=models.CharField(choices=[('pocos', 'Pocos materiales'), ('algunos', 'Algunos materiales'), ('muchos', 'Muchos materiales')], default='algunos', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='integrantes',
            field=models.IntegerField(choices=[(0, 'En grupo'), (1, 'Individual')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preparacion',
            field=models.CharField(choices=[('baja', 'Preparación baja'), ('media', 'Preparación media'), ('alta', 'Preparación alta')], default='media', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='tiempo_duracion',
            field=models.IntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (20, '20 minutos'), (25, '25 minutos'), (30, '30 minutos'), (40, 'Más de 30 minutos')], default=15, null=True, verbose_name='Tiempo aprox. duracion'),
        ),
    ]
