# Generated by Django 2.2.13 on 2020-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200810_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocale',
            name='locale',
            field=models.CharField(choices=[('en_US', 'en_US'), ('es_LA', 'es_LA')], default='en_US', max_length=10),
        ),
    ]
