# Generated by Django 2.2.13 on 2020-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200818_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
