# Generated by Django 2.2.5 on 2020-09-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_language_auto_translate'),
        ('posts', '0014_postlocale_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlocale',
            name='languaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language'),
        ),
    ]
