# Generated by Django 2.2.5 on 2020-09-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postlocale_languaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlocale',
            name='language_id',
        ),
    ]
