# Generated by Django 2.2.5 on 2020-09-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_postlocale_language_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlocale',
            old_name='languaje',
            new_name='language',
        ),
    ]
