# Generated by Django 2.2.5 on 2020-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_languages'),
        ('posts', '0017_auto_20200923_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
    ]
