# Generated by Django 2.2.5 on 2020-10-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='area_id',
            new_name='ar_id',
        ),
    ]
