# Generated by Django 2.2.5 on 2020-10-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_remove_area_top'),
        ('posts', '0019_auto_20201005_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areas.Area'),
            preserve_default=False,
        ),
    ]
