# Generated by Django 2.2.10 on 2020-03-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20200321_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
