# Generated by Django 2.2.10 on 2020-03-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20200322_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language'),
        ),
    ]
