# Generated by Django 2.2.10 on 2020-03-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20200322_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
