# Generated by Django 2.2.10 on 2020-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_auto_20200322_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecode',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
