# Generated by Django 2.2.10 on 2020-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_auto_20200323_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecode',
            name='origin',
            field=models.CharField(choices=[('generated', 'Generated'), ('created', 'Created')], default='generated', max_length=15),
        ),
        migrations.AlterField(
            model_name='languagecode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
