# Generated by Django 2.2.10 on 2020-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_auto_20200325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecode',
            name='origin',
            field=models.CharField(choices=[('generated', 'Generated'), ('created', 'Created')], default='created', max_length=15),
        ),
    ]
