# Generated by Django 2.2.13 on 2020-08-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_auto_20200320_1851'),
        ('languages', '0010_auto_20200325_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
                ('language_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.LanguageCode')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
            ],
        ),
    ]
