# Generated by Django 2.2.13 on 2020-08-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_milestonetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonetranslation',
            name='language_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.LanguageCode'),
        ),
        migrations.AlterField(
            model_name='milestonetranslation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
