# Generated by Django 2.2.13 on 2020-08-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_auto_20200825_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='auto_translate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
