# Generated by Django 2.2.10 on 2020-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='campaign',
            field=models.BooleanField(default=False),
        ),
    ]
