# Generated by Django 2.2.13 on 2020-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200818_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='campaign',
            field=models.BooleanField(default=False),
        ),
    ]
