# Generated by Django 2.2.5 on 2020-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_campaign'),
    ]

    operations = [
    ]
