# Generated by Django 2.2.5 on 2020-08-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200819_2113'),
        ('articles', '0003_articletranslate'),
        ('articles', '0005_demographic'),
    ]

    operations = [
    ]
