# Generated by Django 2.2.13 on 2020-09-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20200831_1450'),
        ('articles', '0006_interaction_instance_id'),
    ]

    operations = [
    ]
