# Generated by Django 2.2.5 on 2020-09-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletranslate',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='max',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='min',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='user',
        ),
        migrations.AlterField(
            model_name='articletranslate',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language'),
        ),
    ]
