# Generated by Django 2.2.5 on 2020-10-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200923_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
    ]
