# Generated by Django 2.2.5 on 2020-10-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201001_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
