# Generated by Django 2.2.13 on 2020-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('review', 'review'), ('rejected', 'rejected'), ('need_changes', 'need changes'), ('published', 'published')], default='draft', max_length=255),
        ),
    ]
