# Generated by Django 2.2.13 on 2021-01-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0021_botsessions'),
        ('articles', '0015_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_sessions.SessionType'),
        ),
    ]
