# Generated by Django 2.2.10 on 2020-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_interaction_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
