# Generated by Django 2.2.10 on 2020-03-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_userinteraction_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'permissions': (('view_all_bots', 'Can view all bots in platform'), ('view_user_bots', 'Can view property user bots in platform'))},
        ),
    ]
