# Generated by Django 2.2.5 on 2020-09-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_auto_20200918_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='Interaction',
            new_name='interaction',
        ),
    ]
