# Generated by Django 2.2.5 on 2020-09-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0013_auto_20200907_0540'),
        ('bots', '0008_auto_20200918_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
    ]
