# Generated by Django 2.2.5 on 2020-09-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_remove_userinteraction_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='person',
            new_name='user',
        ),
    ]
