# Generated by Django 2.2.13 on 2021-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='bot',
            field=models.IntegerField(default=0),
        ),
    ]
