# Generated by Django 2.2.13 on 2021-02-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_auto_20210227_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='bot',
            new_name='bot_id',
        ),
    ]
