# Generated by Django 2.2.10 on 2020-03-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': (('view_all_areas', 'User can view all areas.'),)},
        ),
    ]
