# Generated by Django 2.2.10 on 2020-04-03 23:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20200403_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='anotherColor',
            field=colorfield.fields.ColorField(blank=True, default='#ff0000', null=True),
        ),
    ]
