# Generated by Django 2.2.10 on 2020-04-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20200403_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='anotherColor',
            new_name='another_color',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='backgroundColor',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='pointColor',
            new_name='point_color',
        ),
    ]
