# Generated by Django 2.2.5 on 2020-10-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_auto_20200908_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='topic',
            field=models.IntegerField(null=True),
        ),
    ]
