# Generated by Django 2.2.5 on 2020-10-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_auto_20201001_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
