# Generated by Django 2.2.5 on 2020-10-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('areas', '0011_auto_20201001_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics.Topic'),
        ),
    ]
