# Generated by Django 2.2.5 on 2020-10-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0012_area_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='top',
        ),
    ]
