# Generated by Django 2.2.5 on 2020-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_repo', '0002_auto_20200306_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('AutoTranslated', 'AutoTranslated'), ('Published', 'Published')], default='Draft', max_length=255),
        ),
    ]
