# Generated by Django 2.2.10 on 2020-03-28 20:05

from django.db import migrations


def create_company_group(apps, schema_editor):
    group_models = apps.get_model('auth', 'Group')

    new_group = group_models.objects.create(name='company')
    print(new_group)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_company_group)
    ]
