# Generated by Django 2.2.10 on 2020-04-01 18:55

from django.db import migrations


def set_first_ms_users_permissions_to_company(apps, schema_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    content_type, created = content_type_model.objects.get_or_create(app_label='messenger_users', model='user')
    permissions = permission_model.objects.filter(content_type=content_type,
                                                  codename__in=['view_user'])

    groups = group_model.objects.filter(name__in=['company'])

    for group in groups:
        for permission in permissions:
            group_permission = group.permissions.add(permission)
            print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('messenger_users', '0011_auto_20200401_1755')
    ]

    operations = [
        migrations.RunPython(set_first_ms_users_permissions_to_company)
    ]
