# Generated by Django 2.2.10 on 2020-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('facebook', 'facebook'), ('google', 'google'), ('email', 'email')], default='email', max_length=50)),
                ('login_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=100, unique=True)),
                ('beta', models.BooleanField(default=False)),
            ],
        ),
    ]
