# Generated by Django 2.2.10 on 2020-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_token',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('facebook', 'facebook'), ('google', 'google'), ('custom', 'custom')], default='custom', max_length=50),
        ),
    ]
