# Generated by Django 2.2.10 on 2020-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200426_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
