# Generated by Django 2.2.10 on 2020-03-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0009_auto_20200318_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_state', models.CharField(max_length=25)),
                ('final_state', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messenger_users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pre_register', 'pre_register'), ('in_registration', 'in_registration'), ('user_dead', 'user_dead'), ('wait', 'wait'), ('user_query', 'user_query'), ('broadcast_start', 'broadcast_start'), ('timed_start', 'timed_start'), ('active_session', 'active_session'), ('pre_churn', 'pre_churn'), ('dispatched', 'dispatched'), ('opened', 'opened'), ('follow_up', 'follow_up')], default='wait', help_text='stado', max_length=100, verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='messenger_users.User')),
            ],
        ),
    ]
