# Generated by Django 2.2.13 on 2020-09-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0011_auto_20200401_1755'),
        ('messenger_users', '0011_auto_20200810_0242'),
    ]

    operations = [
    ]
