# Generated by Django 2.2.13 on 2020-10-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_auto_20200329_1527'),
        ('messenger_users', '0014_auto_20200922_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='data_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
