# Generated by Django 2.2.13 on 2020-12-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0017_userchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='bot_channel_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
