# Generated by Django 2.2.13 on 2020-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0019_auto_20201222_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='bot_channel_id',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='user_channel_id',
            field=models.CharField(max_length=20),
        ),
    ]
