# Generated by Django 2.2.13 on 2021-03-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0022_auto_20210310_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
