# Generated by Django 2.2.13 on 2021-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0023_auto_20210319_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='live_chat',
            field=models.BooleanField(default=False),
        ),
    ]
