# Generated by Django 2.2.13 on 2021-03-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0024_userchannel_live_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_chat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_users.UserChannel')),
            ],
        ),
    ]
