# Generated by Django 2.2.13 on 2021-03-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0025_livechat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livechat',
            old_name='user_channel_id',
            new_name='user_channel',
        ),
    ]
