# Generated by Django 3.1.4 on 2021-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0026_auto_20210324_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='userchannel',
            name='last_24window_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='last_channel_interaction',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
