# Generated by Django 2.2.10 on 2020-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestone_second_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='source',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
