# Generated by Django 2.2.10 on 2020-03-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_milestone_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Area'),
        ),
    ]
