# Generated by Django 2.2.5 on 2020-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0006_remove_milestone_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
