# Generated by Django 2.2.5 on 2020-10-28 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0008_auto_20201009_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('step', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
