# Generated by Django 2.2.5 on 2020-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='init_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
