# Generated by Django 2.2.5 on 2020-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0010_milestone_init_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
