# Generated by Django 2.2.5 on 2020-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0010_milestone_init_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='in_risks',
            field=models.BooleanField(default=True),
        ),
    ]
