# Generated by Django 2.2.5 on 2020-11-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0011_session_in_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='first_question',
            field=models.BooleanField(default=True),
        ),
    ]
