# Generated by Django 2.2.13 on 2020-11-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0011_auto_20201107_0132'),
        ('milestones', '0012_session_first_question'),
    ]

    operations = [
    ]
