# Generated by Django 2.2.13 on 2020-12-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0012_milestoneareavalue'),
        ('milestones', '0013_merge_20201112_2248'),
    ]

    operations = [
    ]
