# Generated by Django 2.2.13 on 2020-08-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('quick_replies', 'Quick Replies'), ('save_values_block', 'Save Values Block')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma')),
                ('min', models.IntegerField(default=0, null=True, verbose_name='Min meses')),
                ('max', models.IntegerField(default=72, null=True, verbose_name='Max meses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(to='articles.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('attribute', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('redirect_block', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session'),
        ),
        migrations.CreateModel(
            name='DemographicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma')),
                ('reply', models.TextField()),
                ('value', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Demographic')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Demographic')),
            ],
        ),
    ]
