# Generated by Django 2.2.13 on 2020-09-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
