# Generated by Django 2.2.13 on 2020-08-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '__first__'),
        ('user_sessions', '0002_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='channels',
            field=models.ManyToManyField(to='channels.Channel'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('response', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Reply')),
            ],
        ),
    ]
