# Generated by Django 2.2.13 on 2020-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20200908_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='attribute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
