# Generated by Django 2.2.13 on 2020-08-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0004_auto_20200831_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_sessions.SessionType'),
        ),
    ]
