# Generated by Django 2.2.13 on 2020-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200329_1028'),
        ('licences', '0001_initial'),
        ('user_sessions', '0005_auto_20200908_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographicreply',
            name='demographic',
        ),
        migrations.AddField(
            model_name='session',
            name='entities',
            field=models.ManyToManyField(to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='session',
            name='licences',
            field=models.ManyToManyField(to='licences.License'),
        ),
        migrations.DeleteModel(
            name='DemographicQuestion',
        ),
        migrations.DeleteModel(
            name='DemographicReply',
        ),
    ]
