# Generated by Django 2.2.13 on 2020-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_languages'),
        ('user_sessions', '0006_auto_20200914_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
    ]
