# Generated by Django 2.2.13 on 2020-10-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_auto_20200329_1527'),
        ('user_sessions', '0007_session_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_replies', 'Quick Replies'), ('save_values_block', 'Redirect Chatfuel block'), ('set_attributes', 'Set attribute'), ('user_input', 'Save user input'), ('image', 'Send image'), ('condition', 'Condition'), ('redirect_session', 'Redirect session'), ('consume_service', 'Consume service')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('validation', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('date', 'Date')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SetAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('equal', 'Equal'), ('not_equal', 'Not equal'), ('in', 'Is in')], max_length=50)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
    ]
