# Generated by Django 2.2.13 on 2020-10-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0009_fieldprogramcomment_fieldprogramexclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
