# Generated by Django 2.2.13 on 2020-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0011_auto_20201028_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='interaction',
            name='instance_id_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user_id_id',
            field=models.IntegerField(null=True),
        ),
    ]
