# Generated by Django 2.2.13 on 2020-11-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0013_auto_20201028_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_replies', 'Quick Replies'), ('buttons', 'Buttons'), ('save_values_block', 'Redirect Chatfuel block'), ('set_attributes', 'Set attribute'), ('user_input', 'Save user input'), ('image', 'Send image'), ('condition', 'Condition'), ('redirect_session', 'Redirect session'), ('consume_service', 'Consume service')], max_length=50),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('block_names', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field')),
            ],
        ),
    ]
