# Generated by Django 2.2.13 on 2020-11-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0014_auto_20201108_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectblock',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field'),
        ),
        migrations.AlterField(
            model_name='redirectsession',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field'),
        ),
        migrations.AlterField(
            model_name='redirectsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session'),
        ),
        migrations.AlterField(
            model_name='service',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Field'),
        ),
    ]
