# Generated by Django 2.2.13 on 2020-11-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0016_auto_20201110_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectsession',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session'),
        ),
    ]
