# Generated by Django 2.2.13 on 2020-11-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0018_userinput_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='url',
        ),
        migrations.AddField(
            model_name='service',
            name='request_type',
            field=models.CharField(choices=[('post', 'POST'), ('get', 'GET')], default='post', max_length=5),
        ),
        migrations.CreateModel(
            name='ServiceParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Service')),
            ],
        ),
    ]
