# Generated by Django 2.2.13 on 2020-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0019_auto_20201112_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
