# Generated by Django 2.2.13 on 2020-12-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0020_auto_20201125_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=0)),
                ('session_type', models.CharField(choices=[('welcome', 'Welcome'), ('default', 'Default')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session')),
            ],
        ),
    ]
