# Generated by Django 3.1.4 on 2021-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0027_auto_20210324_0642'),
        ('user_sessions', '0027_auto_20210323_1440'),
    ]

    operations = [
    ]
