# Generated by Django 2.2.10 on 2020-04-01 23:18

from django.db import migrations


def view_all_instances(apps, schema_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    content_type = content_type_model.objects.get(app_label='instances', model='instance')
    permissions = permission_model.objects.filter(content_type=content_type,
                                                  codename__in=['view_instance'])

    print(permissions)

    groups = group_model.objects.filter(name__in=['company'])

    for group in groups:
        for permission in permissions:
            group_permission = group.permissions.add(permission)
            print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0011_auto_20200325_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'permissions': (('view_all_instances', 'User can view all instances'),)},
        ),
        migrations.RunPython(view_all_instances)
    ]
