# Generated by Django 2.2.10 on 2020-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0013_instancefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancefeedback',
            name='migration_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
