# Generated by Django 2.2.10 on 2020-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0014_instancefeedback_migration_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancefeedback',
            name='reference_text',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
