# Generated by Django 2.2.10 on 2020-04-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0015_instancefeedback_reference_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancefeedback',
            name='value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
