# Generated by Django 2.2.10 on 2020-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0016_auto_20200406_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancefeedback',
            name='register_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instancefeedback',
            name='register_type',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
