# Generated by Django 2.2.13 on 2020-09-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_languages'),
        ('instances', '0019_auto_20200521_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='programs.Program'),
        ),
    ]
