# Generated by Django 2.2.13 on 2020-10-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0016_auto_20201017_0209'),
        ('instances', '0020_instance_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceassociationuser',
            name='user_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
    ]
