# Generated by Django 2.2.13 on 2020-10-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0021_instanceassociationuser_user_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceassociationuser',
            name='user_id',
        ),
    ]
