# Generated by Django 2.2.13 on 2020-10-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0022_remove_instanceassociationuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instanceassociationuser',
            old_name='user_temp',
            new_name='user',
        ),
    ]
