# Generated by Django 2.2.5 on 2020-10-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0009_session'),
        ('instances', '0023_auto_20201017_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='sessions',
            field=models.ManyToManyField(to='milestones.Session'),
        ),
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestones.Session'),
        ),
    ]
