# Generated by Django 2.2.13 on 2021-02-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0025_milestoneinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestoneinteraction',
            name='type',
            field=models.CharField(default='hitos_monitoreo', max_length=255),
        ),
    ]
