# Generated by Django 2.2.10 on 2020-03-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('range_min', models.IntegerField(blank=True, default=0, null=True)),
                ('range_max', models.IntegerField(blank=True, default=1, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programs.Program')),
            ],
        ),
    ]
