# Generated by Django 2.2.10 on 2020-03-25 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200325_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
