# Generated by Django 2.2.10 on 2020-03-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200325_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'permissions': (('view_all_programs', 'User can view all programs'), ('view_user_programs', 'User can view programs in your groups'))},
        ),
    ]
