# Generated by Django 2.2.13 on 2020-08-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_auto_20200320_1851'),
        ('programs', '0007_auto_20200330_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMilestoneAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Level')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='milestones',
            field=models.ManyToManyField(through='programs.LevelMilestoneAssociation', to='milestones.Milestone'),
        ),
    ]
