# Generated by Django 2.2.5 on 2020-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_language_auto_translate'),
        ('programs', '0009_attributes_attributetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
