# Generated by Django 2.2.5 on 2020-10-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='program',
        ),
    ]
