# Generated by Django 2.2.5 on 2020-10-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_remove_area_top'),
        ('programs', '0014_program_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='areas',
            field=models.ManyToManyField(to='areas.Area'),
        ),
    ]
