# Generated by Django 2.2.13 on 2020-10-06 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_language_auto_translate'),
        ('programs', '0015_program_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Level')),
            ],
        ),
    ]
