# Generated by Django 2.2.13 on 2020-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_levellanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
