# Generated by Django 2.2.5 on 2020-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
