# Generated by Django 2.2.13 on 2020-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_auto_20201006_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
