# Generated by Django 2.2.13 on 2020-10-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_program_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
