# Generated by Django 2.2.5 on 2020-11-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0010_milestone_init_value'),
        ('programs', '0021_attributes_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramMilestoneValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='milestones',
            field=models.ManyToManyField(through='programs.ProgramMilestoneValue', to='milestones.Milestone'),
        ),
    ]
