# Generated by Django 2.2.5 on 2020-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_auto_20201102_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmilestonevalue',
            name='init',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='programmilestonevalue',
            name='max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='programmilestonevalue',
            name='min',
            field=models.FloatField(default=0),
        ),
    ]
