# Generated by Django 2.2.10 on 2020-03-29 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200329_2342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0006_auto_20200328_2112'),
        ('groups', '0006_botassignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bots',
            field=models.ManyToManyField(through='groups.BotAssignation', to='bots.Bot'),
        ),
        migrations.CreateModel(
            name='ProgramAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='programs',
            field=models.ManyToManyField(through='groups.ProgramAssignation', to='programs.Program'),
        ),
    ]
