# Generated by Django 2.2.10 on 2020-04-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_add_second_permissions_to_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_all_groups', 'User can view all groups'), ('view_user_groups', 'User can view only property groups'))},
        ),
    ]
