# Generated by Django 2.2.10 on 2020-04-01 19:08

from django.db import migrations


def set_third_groups_permissions_to_company(apps, schema_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    content_type = content_type_model.objects.get(app_label='groups', model='group')
    permissions = permission_model.objects.filter(content_type=content_type,
                                                  codename__in=['view_user_groups'])

    print(permissions)

    groups = group_model.objects.filter(name__in=['company'])

    for group in groups:
        for permission in permissions:
            group_permission = group.permissions.add(permission)
            print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20200401_1907'),
    ]

    operations = [
        migrations.RunPython(set_third_groups_permissions_to_company)
    ]
