# Generated by Django 2.2.5 on 2020-10-09 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_attributes_threshold'),
        ('milestones', '0008_auto_20201009_1503'),
        ('groups', '0013_group_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='groups.Group')),
                ('programs', models.ManyToManyField(to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('percent_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
                ('risk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.RiskGroup')),
            ],
        ),
    ]
