# Generated by Django 2.2.5 on 2020-10-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_attributes_threshold'),
        ('groups', '0014_milestonerisk_riskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonerisk',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='milestonerisk',
            name='risk_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.RiskGroup'),
        ),
    ]
