# Generated by Django 2.2.13 on 2020-10-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_assignationmessengeruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignationmessengeruser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
    ]
