# Generated by Django 2.2.5 on 2020-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_auto_20201017_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
