# Generated by Django 2.2.5 on 2020-11-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_auto_20201110_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región/Departamento/Estado'),
        ),
    ]
