# Generated by Django 2.2.5 on 2020-11-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('groups', '0019_auto_20201111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.License'),
        ),
    ]
