# Generated by Django 2.2.10 on 2020-03-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_auto_20190327_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'permissions': (('view_all_attributes', 'User can view all attributes for entities'),)},
        ),
    ]
