# Generated by Django 2.2.13 on 2021-02-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_auto_20200329_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_view',
            field=models.IntegerField(choices=[(0, 'service'), (1, 'data')], default=1),
        ),
    ]
